#!/bin/bash

# list of diretories to copy
TO_COPY=(".pedalboards" "data")

function check {
    local LIST="$(eval $1),"

    for i in ${LIST}; do
        if [[ "${i::-1}" == "$2" ]]; then
            return 0
        fi
    done

    return 1
}

function list_plaforms {
    local PLATS
    for d in mod*/; do
        PLATS+="${d%/}, "
    done

    echo ${PLATS::-2}
}

function list_actions {
    echo "retrieve, deploy"
}

function check_plaform {
    check list_plaforms "$1"
}

function check_action {
    check list_actions "$1"
}

function show_usage {
    echo -e "Usage:\t$0 <platform> <action>"
    echo -e "\tplatform: $(list_plaforms)"
    echo -e "\taction: $(list_actions)"
    exit 1
}

function requirements {
    if ! command -v git > /dev/null; then
        echo "this script requires 'git' command"
        exit 1
    fi

    if ! command -v sshpass > /dev/null; then
        echo "this script requires 'sshpass' command"
        exit 1
    fi
}

function git_me {
    git $@
    if [[ $? != 0 ]]; then
        echo "git command failed probably due conflict"
        echo "please solve it manually and try again"
        echo "the last command was: git $@"
        exit 1
    fi
}

function wait_mod {
    while true; do
        if command -v ifconfig > /dev/null; then
            MOD_IP=$(ifconfig | grep -oE "192\.168\.(50|51)\." | head -1)
        elif command -v ip > /dev/null; then
            MOD_IP=$(ip route | grep -oE "192\.168\.(50|51)\." | head -1)
        else
            echo "command 'ifconfig' or 'ip' is required"
            exit 1
        fi

        if [[ -z ${MOD_IP} ]]; then
            echo "Waiting MOD connection"
            sleep 1
        else
            MOD_IP="${MOD_IP}1"
            break
        fi
    done
    echo "MOD connected at ${MOD_IP}"
}

function copy_key {
    # checking access using user key
    ssh -o "PasswordAuthentication no" root@${MOD_IP} "touch /dev/null" 2>/dev/null
    if [[ $? == 0 ]]; then
        return 0
    fi

    ssh-copy-id root@${MOD_IP}
}

function retrieve {
    echo "retrieving user data from MOD"

    sshpass -p mod ssh root@${MOD_IP} "rm -rf /tmp/new-factory-data && mkdir -p /tmp/new-factory-data"
    for d in ${TO_COPY[@]}; do
        # copy data from MOD to user's PC
        sshpass -p mod scp -r root@${MOD_IP}:/root/$d $1/

        # move current data to /tmp
        # in case something goes wrong is still a way to recover the data yet
        sshpass -p mod ssh root@${MOD_IP} "cp -rf /root/$d /tmp/new-factory-data"

        # recover previous user data
        sshpass -p mod ssh root@${MOD_IP} "[[ -d /root/user-data-backup ]] && rm -rf /root/$d"
        sshpass -p mod ssh root@${MOD_IP} "[[ -d /root/user-data-backup ]] && mv /root/user-data-backup/$d /root"
    done

    # clean old user data
    sshpass -p mod ssh root@${MOD_IP} "[[ -d /root/user-data-backup ]] && mv /root/user-data-backup /tmp"

    # restart services
    sshpass -p mod ssh root@${MOD_IP} "systemctl restart jack2 mod-ui"

    echo "committing changes"
    git commit -a -m "factory user data updated by $(git config user.name)"

    echo "uploading recent changes to remote repository"
    git_me pull --rebase
    git_me push

    echo "done"
}

function deploy {
    echo "downloading the latest user data from remote repository"
    git_me pull --rebase

    sshpass -p mod ssh root@${MOD_IP} "mkdir -p /root/user-data-backup"

    echo "deploying user data to MOD"
    for d in ${TO_COPY[@]}; do
        sshpass -p mod ssh root@${MOD_IP} "mv /root/$d /root/user-data-backup"
        sshpass -p mod scp -r "$1/$d" root@${MOD_IP}:/root/
    done

    sshpass -p mod ssh root@${MOD_IP} "sync"

    echo "restarting services"
    sshpass -p mod ssh root@${MOD_IP} "systemctl restart jack2 mod-ui"

    echo "done"
}

# check arguments
if [[ "$#" != "2" ]] ||
   ! check_plaform "$1" ||
   ! check_action "$2"; then
    show_usage
fi

requirements
wait_mod

# execute action
eval $2 $1
